app:
  accounts:
    one:
      address: HNYU52GEMTY3WACDQTLGGQIMV7XTP2CLNGOXGCPQPZDBI25WWN5BSPNEXA
      passphrase: foot bid fall kite scout prize domain soda tent whip view install deer mountain time lens point invest vivid draft wise kangaroo again about spirit
    two:
      address: K7GWPHBI2MLMAUKRRFGC4P3TKSVK4H3DATCMETSOA4K6UJX4TVSFY2UKM4
      passphrase: love conduct furnace rookie indoor among ostrich public lava copper action fix mask fold marriage broom harbor execute involve news indoor worry radar able basket
